/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TenthousanddaysRoot {
    }
}
declare global {
    interface HTMLTenthousanddaysRootElement extends Components.TenthousanddaysRoot, HTMLStencilElement {
    }
    var HTMLTenthousanddaysRootElement: {
        prototype: HTMLTenthousanddaysRootElement;
        new (): HTMLTenthousanddaysRootElement;
    };
    interface HTMLElementTagNameMap {
        "tenthousanddays-root": HTMLTenthousanddaysRootElement;
    }
}
declare namespace LocalJSX {
    interface TenthousanddaysRoot {
    }
    interface IntrinsicElements {
        "tenthousanddays-root": TenthousanddaysRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tenthousanddays-root": LocalJSX.TenthousanddaysRoot & JSXBase.HTMLAttributes<HTMLTenthousanddaysRootElement>;
        }
    }
}
